### ISSUE TITLE
cannot correct the CTF after Aretomo alignment

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-aretomo#50]
I got the next error when imod CTF correction is carried out with the output of aretomo:
After the errors. I put my ideas about the error

STDERROR:
![image](https://github.com/scipion-em/scipion-em-aretomo/assets/12271438/67895be1-fc85-41a6-bd06-260b03c24c11)

STDOUT: Seems to be good but suddenly stops with a warning
![image](https://github.com/scipion-em/scipion-em-aretomo/assets/12271438/b2bcb0eb-48b9-4e80-b40e-aee536234fc2)

ARETOMO PARAMETERS:
![image](https://github.com/scipion-em/scipion-em-aretomo/assets/12271438/4c8d9c24-1bb4-428d-aa15-2687d82d25de)
![image](https://github.com/scipion-em/scipion-em-aretomo/assets/12271438/5126ae3b-b42a-4472-944d-df2bf9073550)

Here a coarse idea of the test I carried out
![image](https://github.com/scipion-em/scipion-em-aretomo/assets/12271438/b112ceb0-61ec-41b5-92db-7d4c8a216d08)

My guess is that the error is related with aretomo alignment. This is because, 

1. If I use the coarse prealignment of imod, and I correct the CTF with imod, the CTF ends with succeed (see workflow).
2. If the flag -OutputImod 1 is set in the aretomo protocol to generate the .xf files, and they are imported to then correct the ctf with the imported xf files. The CTF correction works see workflow (I created a subset of the tilt series to check this)

![image](https://github.com/scipion-em/scipion-em-aretomo/assets/12271438/2cbaac08-37cf-4304-a59e-4bb732efb28e)

**Comment by azazellochg** [comment]
Hi @Vilax which aretomo version is this? Because they seem to not care about any backward compatibility with previous versions

**Comment by Vilax** [comment]
The information about aretomo:
plugin v: 3.7.1 (devel)
plugin binary v: 1.3.4
pyworkflow 3.3.0

This project was created from scratch, I would not expect problems of retro compatibility.

**Comment by azazellochg** [comment]
Thank you, I'll have a look when I can, likely on the weekend

**Comment by Vilax** [comment]
@azazellochg any update about this?

**Comment by azazellochg** [comment]
Sorry, unfortunately not. This is next on my list though.

**Comment by azazellochg** [comment]
Hi @Vilax I can reproduce your error and warning. The problem is that you are doing tilt angles refinement in aretomo which I would discourage to use. Then in imod protocol tilt angles from tlt (coming from aretomo) and defocus (coming from ctffind) files do not match.

**Comment by azazellochg** [comment]
I'm surprised that imod proceeds with such a mismatch, giving only a warning. I've no idea what angles it will use in such case

**Comment by Vilax** [comment]
I see, this is an issue. Let me think about it. I am also suprise, but at least now we know the problem. Let's think :)

Thanks @azazellochg

**Comment by Vilax** [comment]
I close this issue because it was fixed in  https://github.com/scipion-em/scipion-em-imod/pull/219
