### ISSUE TITLE
Tomo reconstruction: ask if reconstruct the tomograms even/odd are desiredto be reconstructed

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-aretomo#85]
Implications:

* Form param
* Validation or warning: if set Yes and the TS does not have even/odd associated, inform that it is not possible to reconstruct the even/odd tomograms.
* TS alignment is not affected by this, as the complete TS is the only one that should be aligned.

**Comment by JorMaister** [comment]
Should I do this or you take care, @azazellochg?

**Comment by azazellochg** [comment]
please go ahead
Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: ***@***.***

**Comment by JorMaister** [comment]
Ok, I'll add it to my task list. I'll do it together with the removal of the last binary version commented on issue https://github.com/scipion-em/scipion-em-aretomo/issues/84

**Comment by JorMaister** [comment]
Done
