### ISSUE TITLE
Protocol failed: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.

### ISSUE THREAD

**Issue by TomCrey** [scipion-em/scipion-em-aretomo#86]
Hello everyone! 

I've just tried to install and run the AreTomo plugin on a new machine (I've already been using Scipion and AreTomo on other machines without any problems for a few months) and I'm having problems like: **Protocol failed: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.**
I get this kind of output when I try to run the plugin on my data, but also when I test the plugin on this GitHub. 

Below you'll find the test logs from the GitHub.

Thanks for your help!

*************** last 50 lines of STD OUT *********************

RESUMING PROTOCOL -----------------
Protocol starts
Hostname: gre074125
PID: 23160
pyworkflow: 3.6.0
plugin: aretomo
plugin v: 3.9.2(production)
plugin binary v: 1.1.2
currentDir: /mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo
workingDir: Runs/000081_ProtAreTomoAlignRecon
runMode: Continue
          MPI: 1
      threads: 2
 Starting at step: 1
 Running steps 
STARTED: stepsGeneratorStep, step 1, time 2024-07-23 09:23:14.734396
Tomograms calculated for this TS_ID : []
Steps created for TS_ID: TS_54
Steps created for TS_ID: TS_03
Input set closed, all items processed

FINISHED: stepsGeneratorStep, step 1, time 2024-07-23 09:23:34.758523
STARTED: convertInputStep, step 2, time 2024-07-23 09:23:35.068952
------- convertInputStep ts_id: TS_54
FINISHED: convertInputStep, step 2, time 2024-07-23 09:23:35.075880
STARTED: runAreTomoStep, step 3, time 2024-07-23 09:23:35.599693
------- runAreTomoStep ts_id: TS_54
** Running command: **
 /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000081_ProtAreTomoAlignRecon/tmp/TS_54/54.mrc -OutMrc Runs/000081_ProtAreTomoAlignRecon/extra/TS_54/54.mrc -OutImod 0 -AngFile Runs/000081_ProtAreTomoAlignRecon/tmp/TS_54/54.tlt -VolZ 1200 -OutBin 4 -FlipInt 0 -FlipVol 1 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 
FINISHED: runAreTomoStep, step 3, time 2024-07-23 09:23:35.621870
STARTED: createOutputStep, step 4, time 2024-07-23 09:23:36.115015
Getting the dimensions for the first item: None
Getting the dimensions for the first item: Runs/000002_ProtImportTs/extra/54.mrc
FINISHED: createOutputStep, step 4, time 2024-07-23 09:23:36.241359
STARTED: convertInputStep, step 5, time 2024-07-23 09:23:36.671689
------- convertInputStep ts_id: TS_03
FINISHED: convertInputStep, step 5, time 2024-07-23 09:23:36.681856
STARTED: runAreTomoStep, step 6, time 2024-07-23 09:23:37.187775
------- runAreTomoStep ts_id: TS_03
** Running command: **
 /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000081_ProtAreTomoAlignRecon/tmp/TS_03/03.mrc -OutMrc Runs/000081_ProtAreTomoAlignRecon/extra/TS_03/03.mrc -OutImod 0 -AngFile Runs/000081_ProtAreTomoAlignRecon/tmp/TS_03/03.tlt -VolZ 1200 -OutBin 4 -FlipInt 0 -FlipVol 1 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 
FINISHED: runAreTomoStep, step 6, time 2024-07-23 09:23:37.208432
STARTED: createOutputStep, step 7, time 2024-07-23 09:23:37.702405
Getting the dimensions for the first item: Runs/000002_ProtImportTs/extra/03.mrc
FINISHED: createOutputStep, step 7, time 2024-07-23 09:23:37.824986
STARTED: closeOutputSetStep, step 8, time 2024-07-23 09:23:38.234848
FAILED: closeOutputSetStep, step 8, time 2024-07-23 09:23:38.250933
------------------- PROTOCOL FAILED (DONE 8/8)
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 8/8)

*************** end of STD OUT *********************

*************** last 50 lines of STD ERR *********************

/bin/sh: ligne 1: /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125: Aucun fichier ou dossier de ce nom
Aretomo execution failed for tsId TS_54 -> Command ' /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000081_ProtAreTomoAlignRecon/tmp/TS_54/54.mrc -OutMrc Runs/000081_ProtAreTomoAlignRecon/extra/TS_54/54.mrc -OutImod 0 -AngFile Runs/000081_ProtAreTomoAlignRecon/tmp/TS_54/54.tlt -VolZ 1200 -OutBin 4 -FlipInt 0 -FlipVol 1 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 ' returned non-zero exit status 127.
/bin/sh: ligne 1: /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125: Aucun fichier ou dossier de ce nom
Aretomo execution failed for tsId TS_03 -> Command ' /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000081_ProtAreTomoAlignRecon/tmp/TS_03/03.mrc -OutMrc Runs/000081_ProtAreTomoAlignRecon/extra/TS_03/03.mrc -OutImod 0 -AngFile Runs/000081_ProtAreTomoAlignRecon/tmp/TS_03/03.tlt -VolZ 1200 -OutBin 4 -FlipInt 0 -FlipVol 1 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 ' returned non-zero exit status 127.
Couldn't run the code in a thread.
Traceback (most recent call last):
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 153, in run
    self.step._run()  # not self.step.run() , to avoid race conditions
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 254, in _run
    resultFiles = self._runFunc()
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 250, in _runFunc
    return self._func(*self._args)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/aretomo/protocols/protocol_aretomo.py", line 708, in closeOutputSetStep
    raise Exception(msg)
Exception: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.
Protocol failed: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.

*************** end of STD ERR *********************

[   FAILED ] TestAreTomo.test_alignAndReconstruct

Traceback (most recent call last):
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/aretomo/tests/test_protocols_aretomo.py", line 234, in test_alignAndReconstruct
    self.launchProtocol(prot)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 120, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol Align & rec execution failed. See last log lines above for more details.

==> Testing AreTomo:
	- Align only
	- Generate also the interpolated TS
	- Dose weighting
	- No views are excluded
	- CTF not generated
** Running command: 'python3 /home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo" "Runs/000175_ProtAreTomoAlignRecon/logs/run.db" 175 "/mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo/Runs/000175_ProtAreTomoAlignRecon/logs/run.stdout" "/mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo/Runs/000175_ProtAreTomoAlignRecon/logs/run.stderr"'

*************** last 50 lines of STD OUT *********************

RESUMING PROTOCOL -----------------
Protocol starts
Hostname: gre074125
PID: 23240
pyworkflow: 3.6.0
plugin: aretomo
plugin v: 3.9.2(production)
plugin binary v: 1.1.2
currentDir: /mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo
workingDir: Runs/000175_ProtAreTomoAlignRecon
runMode: Continue
          MPI: 1
      threads: 2
 Starting at step: 1
 Running steps 
STARTED: stepsGeneratorStep, step 1, time 2024-07-23 09:23:40.111858
Tomograms calculated for this TS_ID : []
Steps created for TS_ID: TS_54
Steps created for TS_ID: TS_03
Input set closed, all items processed

FINISHED: stepsGeneratorStep, step 1, time 2024-07-23 09:24:00.143324
STARTED: convertInputStep, step 2, time 2024-07-23 09:24:00.449903
------- convertInputStep ts_id: TS_54
FINISHED: convertInputStep, step 2, time 2024-07-23 09:24:00.460355
STARTED: runAreTomoStep, step 3, time 2024-07-23 09:24:00.965784
------- runAreTomoStep ts_id: TS_54
** Running command: **
 /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000175_ProtAreTomoAlignRecon/tmp/TS_54/54.mrc -OutMrc Runs/000175_ProtAreTomoAlignRecon/extra/TS_54/54.mrc -OutImod 0 -AngFile Runs/000175_ProtAreTomoAlignRecon/tmp/TS_54/54.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -ImgDose 3.0 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 
FINISHED: runAreTomoStep, step 3, time 2024-07-23 09:24:00.984865
STARTED: createOutputStep, step 4, time 2024-07-23 09:24:01.480542
Getting the dimensions for the first item: None
Getting the dimensions for the first item: Runs/000002_ProtImportTs/extra/54.mrc
FINISHED: createOutputStep, step 4, time 2024-07-23 09:24:01.597513
STARTED: convertInputStep, step 5, time 2024-07-23 09:24:02.020577
------- convertInputStep ts_id: TS_03
FINISHED: convertInputStep, step 5, time 2024-07-23 09:24:02.028037
STARTED: runAreTomoStep, step 6, time 2024-07-23 09:24:02.537205
------- runAreTomoStep ts_id: TS_03
** Running command: **
 /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000175_ProtAreTomoAlignRecon/tmp/TS_03/03.mrc -OutMrc Runs/000175_ProtAreTomoAlignRecon/extra/TS_03/03.mrc -OutImod 0 -AngFile Runs/000175_ProtAreTomoAlignRecon/tmp/TS_03/03.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -ImgDose 3.0 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 
FINISHED: runAreTomoStep, step 6, time 2024-07-23 09:24:02.558551
STARTED: createOutputStep, step 7, time 2024-07-23 09:24:03.077521
Getting the dimensions for the first item: Runs/000002_ProtImportTs/extra/03.mrc
FINISHED: createOutputStep, step 7, time 2024-07-23 09:24:03.156994
STARTED: closeOutputSetStep, step 8, time 2024-07-23 09:24:03.601812
FAILED: closeOutputSetStep, step 8, time 2024-07-23 09:24:03.616767
------------------- PROTOCOL FAILED (DONE 8/8)
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 8/8)

*************** end of STD OUT *********************

*************** last 50 lines of STD ERR *********************

/bin/sh: ligne 1: /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125: Aucun fichier ou dossier de ce nom
Aretomo execution failed for tsId TS_54 -> Command ' /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000175_ProtAreTomoAlignRecon/tmp/TS_54/54.mrc -OutMrc Runs/000175_ProtAreTomoAlignRecon/extra/TS_54/54.mrc -OutImod 0 -AngFile Runs/000175_ProtAreTomoAlignRecon/tmp/TS_54/54.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -ImgDose 3.0 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 ' returned non-zero exit status 127.
/bin/sh: ligne 1: /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125: Aucun fichier ou dossier de ce nom
Aretomo execution failed for tsId TS_03 -> Command ' /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000175_ProtAreTomoAlignRecon/tmp/TS_03/03.mrc -OutMrc Runs/000175_ProtAreTomoAlignRecon/extra/TS_03/03.mrc -OutImod 0 -AngFile Runs/000175_ProtAreTomoAlignRecon/tmp/TS_03/03.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.1 -Gpu 0 -ImgDose 3.0 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 ' returned non-zero exit status 127.
Couldn't run the code in a thread.
Traceback (most recent call last):
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 153, in run
    self.step._run()  # not self.step.run() , to avoid race conditions
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 254, in _run
    resultFiles = self._runFunc()
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 250, in _runFunc
    return self._func(*self._args)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/aretomo/protocols/protocol_aretomo.py", line 708, in closeOutputSetStep
    raise Exception(msg)
Exception: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.
Protocol failed: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.

*************** end of STD ERR *********************

[   FAILED ] TestAreTomo.test_align_01

Traceback (most recent call last):
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/aretomo/tests/test_protocols_aretomo.py", line 129, in test_align_01
    self.launchProtocol(prot)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 120, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol Align only, no CTF execution failed. See last log lines above for more details.

==> Testing AreTomo:
	- Align only
	- Generate also the interpolated TS
	- No dose weighting
	- Some views are excluded
	- CTF generated
** Running command: 'python3 /home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo" "Runs/000269_ProtAreTomoAlignRecon/logs/run.db" 269 "/mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo/Runs/000269_ProtAreTomoAlignRecon/logs/run.stdout" "/mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo/Runs/000269_ProtAreTomoAlignRecon/logs/run.stderr"'

*************** last 50 lines of STD OUT *********************

RESUMING PROTOCOL -----------------
Protocol starts
Hostname: gre074125
PID: 23352
pyworkflow: 3.6.0
plugin: aretomo
plugin v: 3.9.2(production)
plugin binary v: 1.1.2
currentDir: /mnt/data/Data_TOM/ScipionUserData/projects/TestAreTomo
workingDir: Runs/000269_ProtAreTomoAlignRecon
runMode: Continue
          MPI: 1
      threads: 2
 Starting at step: 1
 Running steps 
STARTED: stepsGeneratorStep, step 1, time 2024-07-23 09:24:05.425722
Tomograms calculated for this TS_ID : []
Steps created for TS_ID: TS_54
Steps created for TS_ID: TS_03
Input set closed, all items processed

FINISHED: stepsGeneratorStep, step 1, time 2024-07-23 09:24:25.457325
STARTED: convertInputStep, step 2, time 2024-07-23 09:24:25.766893
------- convertInputStep ts_id: TS_54
FINISHED: convertInputStep, step 2, time 2024-07-23 09:24:25.777083
STARTED: runAreTomoStep, step 3, time 2024-07-23 09:24:26.283694
------- runAreTomoStep ts_id: TS_54
** Running command: **
 /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000269_ProtAreTomoAlignRecon/tmp/TS_54/54.mrc -OutMrc Runs/000269_ProtAreTomoAlignRecon/extra/TS_54/54.mrc -OutImod 0 -AngFile Runs/000269_ProtAreTomoAlignRecon/tmp/TS_54/54.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.9 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 
FINISHED: runAreTomoStep, step 3, time 2024-07-23 09:24:26.306210
STARTED: createOutputStep, step 4, time 2024-07-23 09:24:26.799694
Getting the dimensions for the first item: None
Getting the dimensions for the first item: Runs/000002_ProtImportTs/extra/54.mrc
FINISHED: createOutputStep, step 4, time 2024-07-23 09:24:26.928959
STARTED: convertInputStep, step 5, time 2024-07-23 09:24:27.315612
------- convertInputStep ts_id: TS_03
FINISHED: convertInputStep, step 5, time 2024-07-23 09:24:27.325403
STARTED: runAreTomoStep, step 6, time 2024-07-23 09:24:27.831321
------- runAreTomoStep ts_id: TS_03
** Running command: **
 /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000269_ProtAreTomoAlignRecon/tmp/TS_03/03.mrc -OutMrc Runs/000269_ProtAreTomoAlignRecon/extra/TS_03/03.mrc -OutImod 0 -AngFile Runs/000269_ProtAreTomoAlignRecon/tmp/TS_03/03.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.9 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 
FINISHED: runAreTomoStep, step 6, time 2024-07-23 09:24:27.852509
STARTED: createOutputStep, step 7, time 2024-07-23 09:24:28.348261
Getting the dimensions for the first item: Runs/000002_ProtImportTs/extra/03.mrc
FINISHED: createOutputStep, step 7, time 2024-07-23 09:24:28.412628
STARTED: closeOutputSetStep, step 8, time 2024-07-23 09:24:28.864483
FAILED: closeOutputSetStep, step 8, time 2024-07-23 09:24:28.879686
------------------- PROTOCOL FAILED (DONE 8/8)
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 8/8)

*************** end of STD OUT *********************

*************** last 50 lines of STD ERR *********************

/bin/sh: ligne 1: /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125: Aucun fichier ou dossier de ce nom
Aretomo execution failed for tsId TS_54 -> Command ' /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000269_ProtAreTomoAlignRecon/tmp/TS_54/54.mrc -OutMrc Runs/000269_ProtAreTomoAlignRecon/extra/TS_54/54.mrc -OutImod 0 -AngFile Runs/000269_ProtAreTomoAlignRecon/tmp/TS_54/54.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.9 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 ' returned non-zero exit status 127.
/bin/sh: ligne 1: /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125: Aucun fichier ou dossier de ce nom
Aretomo execution failed for tsId TS_03 -> Command ' /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125 -InMrc Runs/000269_ProtAreTomoAlignRecon/tmp/TS_03/03.mrc -OutMrc Runs/000269_ProtAreTomoAlignRecon/extra/TS_03/03.mrc -OutImod 0 -AngFile Runs/000269_ProtAreTomoAlignRecon/tmp/TS_03/03.tlt -VolZ 0 -OutBin 4 -FlipInt 0 -FlipVol 0 -PixSize 1.35 -Kv 300.0 -DarkTol 0.9 -Gpu 0 -Cs 2.7 -Align 1 -TiltAxis 85.3 0 -TiltCor 0 -AlignZ 900 -Sart 15 5 ' returned non-zero exit status 127.
Couldn't run the code in a thread.
Traceback (most recent call last):
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 153, in run
    self.step._run()  # not self.step.run() , to avoid race conditions
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 254, in _run
    resultFiles = self._runFunc()
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 250, in _runFunc
    return self._func(*self._args)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/aretomo/protocols/protocol_aretomo.py", line 708, in closeOutputSetStep
    raise Exception(msg)
Exception: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.
Protocol failed: All the introduced Tilt Series were not correctly aligned and/or all the corresponding tomograms were not correctly generated.

*************** end of STD ERR *********************

[   FAILED ] TestAreTomo.test_align_02

Traceback (most recent call last):
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/aretomo/tests/test_protocols_aretomo.py", line 187, in test_align_02
    self.launchProtocol(prot)
  File "/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 120, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol Align only, exclude views execution failed. See last log lines above for more details.

**Comment by azazellochg** [comment]
Hi @TomCrey 
The error is pretty obvious:
```
/bin/sh: ligne 1: /home/photosymbiosis/Documents/Programs/Scipion/software/em/aretomo2-1.1.2/bin/AreTomo2_1.1.2_Cuda125: Aucun fichier ou dossier de ce nom
```
`scipion3 config -p aretomo` will print you the current config. You will need to adjust the config to match the binary you want to use

**Comment by TomCrey** [comment]
Hi @azazellochg
Thanks for your help, a fresh eye always helps to find the error hidden in those endless logs (especially when you've been at it for hours...).

When I execute the command you gave me I get this output : 

```
photosymbiosis@gre074125:~$ scipion3 config -p aretomo
Scipion v3.5.0 - Eugenius
Traceback (most recent call last):
  File “/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/scipion/__main__.py”, line 505, in <module>
    main()
  File “/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/scipion/__main__.py”, line 323, in main
    main(sys.argv[2:])
  File “/home/photosymbiosis/miniconda3/envs/scipion3/lib/python3.8/site-packages/scipion/scripts/config.py”, line 98, in main
    plugin._defineVariables()
TypeError: _defineVariables() missing 1 required positional argument: 'cls'
Error at main: _defineVariables() missing 1 required positional argument: 'cls'

```
So I'm still lost...

**Comment by azazellochg** [comment]
Okay. Actually this command is broken for me as well. What you can do is:
/home/photosymbiosis/Documents/Programs/Scipion/config/scipion.conf and add lines like:
```
ARETOMO_BIN = AreTomo2_1.1.2_Cuda121
ARETOMO_CUDA_LIB = /public/EM/CUDA/cuda-12.1/lib64
```
of course, the cuda path/version should be the one you use on the machine.

**Comment by azazellochg** [comment]
We found the problem for the last `Error at main: _defineVariables() missing 1 required positional argument: 'cls'` error. It is aretomo plugin error which we will fix now

**Comment by azazellochg** [comment]
@TomCrey if you update the plugin to 3.9.3 `scipion3 config -p aretomo` should work. It will print you the current configuration.

**Comment by TomCrey** [comment]
Everything works, thank you very much for your help @azazellochg !
